import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { getSession } from './auth'
import './globals.css'
import AuthProvider from './providers/auth'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <html lang='en'>
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider session={session}>
          <main className='h-dvh w-dvw'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
